apiVersion: v1
kind: Service
metadata:
  name: my-test-app-svc
spec:
  selector:
    app: my-test-app
  ports:
    - protocol: TCP
      nodePort: 30080
      port: 80
      targetPort: 8080
  type: NodePort
